### ISSUE TITLE
Feature Request: Add parser to load font files (woff, woff2, otf, etc)

### ISSUE THREAD

**Issue by pbesteves** [UX-and-I/storybook-design-token#17]
I am using some custom fonts on a project I am working on and I need to load an .otf file.

**Comment by Sqrrl** [comment]
Hey. That's a big bullet on my list. Will think about a solution as soon as possible.

**Comment by pbesteves** [comment]
Hi! I believe that using the [url-loader](https://github.com/webpack-contrib/url-loader) or [file-loader](https://github.com/webpack-contrib/file-loader) for webpack would be a nice approach. From what I've seen, currently the addon only used the raw-loader.

**Comment by Sqrrl** [comment]
Hey. 

It's been a while since your request, but maybe you'd like to check out the v1 beta. It comes with a way to inject custom fonts.

`yarn add storybook-design-token@next`
or
`npm add storybook-design-token@next`

Readme is here: https://github.com/UX-and-I/storybook-design-token/tree/v1
Style injection is described here: https://github.com/UX-and-I/storybook-design-token/tree/v1#advanced-configuration
