### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [UX-and-I/storybook-design-token#206]
Hey all! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by Matt-Scoville** [comment]
Is there any update on this?

Since Storybook 8 has now been released.  I'm looking to update my projects Storybook and it is telling me that the storybook-design-token addon is incompatible since it requires a different major version.  It does seem to work however.

**Comment by Sqrrl** [comment]
Just merged https://github.com/UX-and-I/storybook-design-token/pull/210. Thanks to @sod. Released with v3.1.0

**Comment by sod** [comment]
Thanks a lot for releasing so fast @Sqrrl.

Who lands here because they get errors with storybook-design-token@3.1.0 + storybook@8 - be aware that storybook v8 removed mdx1 and mdx+csf support. So mdx files may have to be upgraded.

E.g.
* we had to rename our `<name>.stories.mdx` files to `<name>.mdx` (remove the `stories.`) as storybook removed cfs support in mdx files
* we had to remove `isTemplate` from `<Meta title="<title>" isTemplate />`, as that property was removed

see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mdx-related-changes
