### ISSUE TITLE
Feature Request: importing values from a `.ts` file

### ISSUE THREAD

**Issue by AnnekaSillitoe** [UX-and-I/storybook-design-token#46]
We have our tokens in a `.ts` file as we're using https://stitches.dev/

It would be great to be able to pick up our tokens from our file to use in Storybook for both documentation purposes and customisation of components.

Is there any plan to add the ability to do this?

**Comment by Sqrrl** [comment]
Hey, thanks for your request.

There are definitely plans to support some kind of JSON design token specification. Right now I am considering to implement a [Theo](https://github.com/salesforce-ux/theo) parser, since it is reasonably widespread.

Unfortunately it wouldn't be practical to implement parsers for all the different formats used by various CSS-in-JS libraries. But feel free to open a pull request.
