### ISSUE TITLE
DesignTokenDocBlock not working with npm

### ISSUE THREAD

**Issue by brunaschneiders** [UX-and-I/storybook-design-token#63]
Hello all!

I'm having trouble us
ing DesignTokenDocBlock installing via npm. This error appears on the console:
![Screenshot from 2021-10-07 17-30-44](https://user-images.githubusercontent.com/64864277/136457713-d170439f-1bc5-407a-a669-e52605c33686.png)
![Screenshot from 2021-10-07 17-31-36](https://user-images.githubusercontent.com/64864277/136457833-07beea1b-be22-4674-9adc-876591aa8fdb.png)

The problem doesn't happen when I install via yarn, but I need it to work with npm..

Can someone help me, please?

**Comment by Smolations** [comment]
I have actually encountered this same issue recently. Hadn't realized it may have been happening since this issue was reported in October. It doesn't seem to make a difference when static storybook is built/deployed, but I am seeing this error in development and it prevents the addon panel from appearing (and somehow breaks a figma panel we install as well 🤔 ).

**Comment by Smolations** [comment]
Following up, I just asked a teammate to see if he was seeing the same issue, and he could not. Therefore I tried deleting my `node_modules` and reinstalling at that eliminated the error in development. @brunaschneiders Maybe try that and see if it works for you?

**Comment by Sqrrl** [comment]
It's been a while. I'm closing this issues. Please re-open if the problem still exists.
